### ISSUE TITLE
Chrome 72 detects as Safari again

### ISSUE THREAD

**Issue by radicand** [mbasso/react-browser-detection#13]
Follow up to #11, I'm getting Safari detection on Chrome now (Chrome 72, Mac). Below is my userAgent string:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36`

**Comment by mbasso** [comment]
Hi @radicand,
I've tried to reproduce this issue but I wasn't able to. I've created [this](https://codesandbox.io/s/7j71ono51?fontsize=14) to try it out. Can you please confirm that it doesn't work for you?

**Comment by radicand** [comment]
Thanks @mbasso - I kept seeing the error but your test passed for me. I ended up nuking my modules folder and having them install fresh and it works fine now - apparently a caching issue. Thanks for taking the time to make a test-case for me to validate.
