### ISSUE TITLE
React 16: throws errors with example

### ISSUE THREAD

**Issue by stevematdavies** [mbasso/react-browser-detection#3]
`Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `BrowserDetection`, expected `object`. in BrowserDetection`

**Comment by mbasso** [comment]
Hi @stevematdavies,
unfortunately I'm unable to reproduce this issue, can you please post here the code that throws this error?
Are you using `BrowserDetection` with an object as child? (docs [here](https://github.com/mbasso/react-browser-detection#props))

```js
import React, { Component } from 'react';
import BrowserDetection from 'react-browser-detection';

export default class App extends Component {
  render() {
    return (
      <BrowserDetection>
        {{
          chrome: () => <div>Chrome is fantastic!</div>,
          default: (browser) => <div>Hi {browser}!</div>,
        }}
      </BrowserDetection>
    );
  }
}
```
