### ISSUE TITLE
Question: How to set state depending on browser? 

### ISSUE THREAD

**Issue by kejtizuki** [mbasso/react-browser-detection#7]
Hi, 
I was trying to set state when some browser is detected, however I can't do that inside browserHandler, there is a problem with "this". Could you please help?

**Comment by mbasso** [comment]
Hi @kejtizuki,
can you please share the snippet of code that throws the exception so I can help you?
I'll post here an example that works fine:

```js
import React, { Component } from 'react';
import BrowserDetection from 'react-browser-detection';

export default class App extends Component {
  state = {
    browser: null,
  }

  browserHandler = {
    default: (browser) => {
      this.setState({
        browser,
      });
      return null;
    }
  }

  render() {
    return (
      <div>
        browser: {this.state.browser}
        <BrowserDetection>
          {this.browserHandler}
        </BrowserDetection>
      </div>
    );
  }
}
```

Please note that the `default` handler (so the `setState`) is executed only once, if you want to execute the handler at every render of the `App` component you can set the [`once`](https://github.com/mbasso/react-browser-detection#props) prop to `false`:

```js
<BrowserDetection once={false}>
  {this.browserHandler}
</BrowserDetection>
```

**Comment by mbasso** [comment]
@kejtizuki news about this?
