### ISSUE TITLE
Edge detected as Safari

### ISSUE THREAD

**Issue by dirkdevriendt** [mbasso/react-browser-detection#8]
FYI: due to its rather extensive UserAgent, the Edge browser (v41) is currently detected as being Safari

Example Edge UserAgent:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299`

**Comment by mbasso** [comment]
Hi @dirkdevriendt,
thank you for opening this issue. I'll fix it in the weekend, as soon as possible

**Comment by dirkdevriendt** [comment]
Thanks for replying (and your opensource effort in general, it's really appreciated),
it's not an issue for me and no urgency at all, I just thought you'd like to be informed.

**Comment by mbasso** [comment]
Just fixed 🎉 
Thank you!
